"use client";

import { useState } from "react";
import {
  Activity, ArrowDown, ArrowLeft, Banknote, Check, CheckCircle2,
  ChevronLeft, CircleAlert, ClipboardCheck, FileText, HeartPulse, Landmark,
  RefreshCw, ShieldCheck, Stethoscope, Users, WalletCards,
} from "lucide-react";

type Role = "overview" | "patient" | "specialist" | "admin" | "bank" | "investor";
type DemoState = "bankReview" | "moreInfo" | "approved" | "providerVerified" | "disbursed" | "treatment" | "completed" | "rejected";
type Page = "home" | "eligibility" | "consultation" | "assessment" | "application" | "status" | "case" | "money" | "criteria" | "decisions" | "funding";

const roles: { id: Role; label: string; icon: typeof HeartPulse }[] = [
  { id: "overview", label: "نظرة عامة", icon: Activity }, { id: "patient", label: "المريض", icon: HeartPulse },
  { id: "specialist", label: "الأخصائي", icon: Stethoscope }, { id: "admin", label: "إدارة MedNova", icon: ClipboardCheck },
  { id: "bank", label: "شريك البنك", icon: Landmark }, { id: "investor", label: "التمويل / المستثمر", icon: WalletCards },
];

const statusMeta: Record<DemoState, { label: string; tone: string }> = {
  bankReview: { label: "قيد مراجعة البنك", tone: "bg-amber-100 text-amber-800" }, moreInfo: { label: "معلومات إضافية مطلوبة", tone: "bg-orange-100 text-orange-800" },
  approved: { label: "تمت الموافقة — بانتظار التحقق", tone: "bg-emerald-100 text-emerald-800" }, providerVerified: { label: "جاهز للصرف", tone: "bg-teal-100 text-teal-800" },
  disbursed: { label: "تم الصرف", tone: "bg-blue-100 text-blue-800" }, treatment: { label: "العلاج جارٍ", tone: "bg-[#e6f6f2] text-[#1F6069]" },
  completed: { label: "اكتمل العلاج", tone: "bg-slate-100 text-slate-700" }, rejected: { label: "لم تتم الموافقة", tone: "bg-rose-100 text-rose-800" },
};

function StatusBadge({ state }: { state: DemoState }) { const s = statusMeta[state]; return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold ${s.tone}`}>{s.label}</span>; }
function MetricCard({ label, value, icon: Icon, accent = "text-[#32A88D]" }: { label: string; value: string; icon: typeof Activity; accent?: string }) { return <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><span className="text-sm text-gray-500">{label}</span><Icon className={`h-5 w-5 ${accent}`} /></div><div className="mt-4 text-2xl font-bold text-gray-900">{value}</div></div>; }
function Panel({ title, children, action }: { title?: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6">{title && <div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold text-gray-900">{title}</h2>{action}</div>}{children}</section>; }
function Button({ children, onClick, secondary = false }: { children: React.ReactNode; onClick?: () => void; secondary?: boolean }) { return <button onClick={onClick} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition ${secondary ? "border border-gray-200 bg-white text-gray-700 hover:bg-gray-50" : "bg-[#32A88D] text-white hover:bg-[#2a9278]"}`}>{children}</button>; }

const DISCLAIMER = "هذا نموذج تشغيلي مقترح للنقاش. التمويل والاستثمار وحفظ الأموال والصرف والسداد والمسؤوليات التنظيمية تخضع للاتفاق النهائي مع البنك والتحقق القانوني والتنظيمي.";

export function FinancingPrototype() {
  const [role, setRole] = useState<Role>("overview"); const [page, setPage] = useState<Page>("home"); const [state, setState] = useState<DemoState>("bankReview"); const [amount, setAmount] = useState("750"); const [flow, setFlow] = useState<"patient" | "provider" | "controlled">("provider");
  const reset = () => { setState("bankReview"); setPage("home"); setRole("overview"); setAmount("750"); };
  const go = (next: Page) => setPage(next);
  const title = roles.find((item) => item.id === role)?.label ?? "";
  return <main className="min-h-screen bg-[#f7faf9] text-gray-900" dir="rtl">
    <header className="sticky top-0 z-30 border-b border-gray-100 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-3 px-4 py-3 sm:px-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-[#32A88D] to-[#1F6069] text-lg font-bold text-white">M</div><div><p className="font-bold text-[#1F6069]">MedNova Care</p><p className="text-xs text-gray-500">Healthcare Financing · Concept Demo</p></div></div><StatusBadge state={state} /></div></header>
    <div className="mx-auto grid max-w-[1500px] lg:grid-cols-[250px_1fr]">
      <aside className="border-l border-gray-100 bg-white p-4 lg:min-h-[calc(100vh-65px)]"><p className="mb-3 px-3 text-xs font-bold tracking-wide text-gray-400">تبديل منظور العرض</p><nav className="flex gap-2 overflow-x-auto lg:flex-col">{roles.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => { setRole(id); setPage("home"); }} className={`flex shrink-0 items-center gap-3 rounded-xl px-3 py-3 text-right text-sm font-bold transition ${role === id ? "bg-[#e6f6f2] text-[#1F6069]" : "text-gray-600 hover:bg-gray-50"}`}><Icon className="h-5 w-5" />{label}</button>)}</nav><div className="mt-5 hidden rounded-xl bg-[#f4fbf9] p-3 text-xs leading-5 text-[#1F6069] lg:block"><b>نموذج مقترح</b><br />لم يتم افتراض أن MedNova مقرض أو أمين حفظ للأموال.</div></aside>
      <section className="min-w-0 p-4 sm:p-6 lg:p-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-[#32A88D]">{title}</p><h1 className="text-2xl font-bold sm:text-3xl">{pageTitle(role, page)}</h1></div><div className="flex gap-2"><Button secondary onClick={() => go("money")}>تدفق الأموال</Button><Button secondary onClick={() => go("decisions")}>قرارات مفتوحة</Button></div></div>
        {page === "money" ? <MoneyFlow flow={flow} setFlow={setFlow} /> : page === "criteria" ? <Criteria /> : page === "decisions" ? <OpenDecisions /> : page === "funding" ? <Funding state={state} /> : role === "overview" ? <Overview go={go} /> : role === "patient" ? <Patient page={page} go={go} state={state} amount={amount} setAmount={setAmount} /> : role === "specialist" ? <Specialist state={state} /> : role === "admin" ? <Admin state={state} go={go} /> : role === "bank" ? <Bank state={state} setState={setState} /> : <Investor state={state} go={go} />}
        <div className="mt-8 rounded-xl border border-[#bde5da] bg-[#f1faf7] px-4 py-3 text-xs leading-5 text-[#35645a]"><b>تنبيه العرض:</b> {DISCLAIMER}</div>
      </section>
    </div><DemoControls state={state} setState={setState} reset={reset} />
  </main>;
}

function pageTitle(role: Role, page: Page) { if (page === "money") return "تدفق الأموال والمسؤوليات"; if (page === "criteria") return "معايير التمويل الأولية"; if (page === "decisions") return "القرارات المفتوحة مع البنك"; if (page === "funding") return "هيكل التمويل المقترح"; const titles: Record<Role, string> = { overview: "كيف يعمل تمويل الرعاية الصحية", patient: "رحلتي الصحية والتمويلية", specialist: "بوابة الأخصائي والرعاية", admin: "عمليات تمويل الرعاية الصحية", bank: "بوابة الشريك المصرفي", investor: "مفهوم الشريك التمويلي" }; return titles[role]; }

function Overview({ go }: { go: (p: Page) => void }) { const steps = ["المريض", "التقييم الطبي", "الأهلية الطبية", "طلب التمويل", "مراجعة MedNova", "مراجعة البنك", "التحقق من المزود", "الصرف", "العلاج", "السداد"]; return <div className="space-y-6"><Panel><div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><div><span className="rounded-full bg-[#e6f6f2] px-3 py-1 text-xs font-bold text-[#1F6069]">مقترح شراكة مصرفية</span><h2 className="mt-4 text-3xl font-bold leading-tight">الوصول للعلاج الذي تحتاجه عبر حل تمويل صحي منظّم.</h2><p className="mt-3 max-w-2xl leading-7 text-gray-600">نفصل بوضوح بين الحاجة الطبية، وقرار التمويل البنكي، وتوفر رأس المال — دون ضمان للتمويل أو افتراض هيكل قانوني نهائي.</p><div className="mt-5 flex flex-wrap gap-3"><Button onClick={() => go("eligibility")}>ابدأ رحلة المريض <ChevronLeft className="h-4 w-4" /></Button><Button secondary onClick={() => go("money")}>استكشف النموذج المالي</Button></div></div><div className="rounded-2xl bg-gradient-to-br from-[#32A88D] to-[#1F6069] p-6 text-white"><p className="text-sm opacity-80">ثلاثة قرارات مستقلة</p><div className="mt-5 space-y-4">{["الأهلية الطبية — من الحاجة والتقرير", "الأهلية التمويلية — قرار البنك", "توفر التمويل — الهيكل المعتمد"].map((x, i) => <div className="flex gap-3" key={x}><span className="grid h-6 w-6 place-items-center rounded-full bg-white/20 text-xs">{i + 1}</span><span className="text-sm font-bold">{x}</span></div>)}</div></div></div></Panel><Panel title="رحلة الرعاية والتمويل المقترحة"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{steps.map((step, i) => <div key={step} className="flex items-center gap-2 rounded-xl bg-gray-50 p-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-white text-xs font-bold text-[#32A88D] shadow-sm">{i + 1}</span><span className="text-xs font-bold">{step}</span></div>)}</div></Panel><div className="grid gap-5 lg:grid-cols-3"><DecisionCard title="الاحتياج الطبي" value="تقرير أخصائي معتمد" tone="teal" /><DecisionCard title="قرار التمويل" value="بمعايير البنك — للتأكيد" tone="amber" /><DecisionCard title="توفر رأس المال" value="وفق هيكل التمويل المعتمد" tone="blue" /></div></div>; }
function DecisionCard({ title, value, tone }: { title: string; value: string; tone: "teal" | "amber" | "blue" }) { const c = { teal: "border-[#aee1d4] bg-[#f1faf7]", amber: "border-amber-200 bg-amber-50", blue: "border-blue-200 bg-blue-50" }[tone]; return <div className={`rounded-2xl border p-5 ${c}`}><p className="text-sm font-bold">{title}</p><p className="mt-2 text-sm text-gray-600">{value}</p><p className="mt-4 text-xs text-gray-500">قرار منفصل ضمن النموذج المقترح</p></div>; }

function Patient({ page, go, state, amount, setAmount }: { page: Page; go: (p: Page) => void; state: DemoState; amount: string; setAmount: (v: string) => void }) {
  if (page === "eligibility") return <Panel title="تحقق مبدئي من الأهلية"><StepProgress active={1} /><div className="mt-6 grid gap-3">{["هل تطلب تمويلاً لخدمة طبية أو تأهيلية؟", "هل العلاج ضروري طبياً؟", "هل لديك تقييم طبي أو أخصائي؟"].map(q => <label key={q} className="flex items-center justify-between rounded-xl border border-gray-200 p-4 text-sm font-medium"><span>{q}</span><span className="flex gap-2"><button className="rounded-lg bg-[#e6f6f2] px-3 py-1.5 text-[#1F6069]">نعم</button><button className="rounded-lg bg-gray-100 px-3 py-1.5">لا أعلم</button></span></label>)}</div><p className="mt-5 text-xs text-gray-500">الأهلية التمويلية النهائية خاضعة للتقييم الطبي وموافقة البنك.</p><div className="mt-5"><Button onClick={() => go("consultation")}>تابع للاستشارة التشخيصية</Button></div></Panel>;
  if (page === "consultation") return <Panel title="استشارة تشخيصية"><StepProgress active={2} /><div className="mt-6 grid gap-4 md:grid-cols-2"><Info label="الأخصائي المختار" value="د. سارة البلوشية · طب التأهيل" /><Info label="نوع الاستشارة" value="فيديو · تقييم تشخيصي" /><Info label="الموعد المتاح" value="الأحد، 10:30 صباحاً" /><Info label="رسم الاستشارة" value="OMR 20" /></div><div className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">هذه الاستشارة للتقييم الطبي وأهلية التمويل؛ لا تضمن التمويل أو تغطية العلاج بالكامل.</div><div className="mt-5"><Button onClick={() => go("assessment")}>تأكيد الحجز</Button></div></Panel>;
  if (page === "assessment") return <Panel title="ملخص التقييم الطبي"><StepProgress active={3} /><div className="mt-5 grid gap-4 md:grid-cols-2"><Info label="الحالة" value="إصابة في الركبة بعد جراحة" /><Info label="الشدة" value="متوسطة — تحتاج إعادة تأهيل" /><Info label="الضرورة الطبية" value="موثقة سريرياً" /><Info label="التدخل الموصى به" value="برنامج علاج طبيعي وتأهيلي" /><Info label="الحاجة المالية التقديرية" value="OMR 750 (تقديرية)" /><Info label="تاريخ التقرير" value="14 سبتمبر 2026" /></div><p className="mt-5 text-xs text-gray-500">المبلغ والشروط النهائية خاضعة لتقييم شريك التمويل.</p><div className="mt-5"><Button onClick={() => go("application")}>عرض نتيجة الأهلية الطبية</Button></div></Panel>;
  if (page === "application") return <Panel title="طلب التمويل الصحي"><StepProgress active={4} /><div className="mt-6 grid gap-5 md:grid-cols-2"><Input label="المبلغ المطلوب (OMR)" value={amount} onChange={setAmount} /><Info label="مدة التمويل" value="يحددها شريك التمويل" /><Info label="الرسم التشغيلي" value="قيد التأكيد" /><Info label="الغرض" value="تأهيل الركبة" /></div><h3 className="mt-7 font-bold">المستندات</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{["البطاقة الشخصية — تم الرفع", "إثبات الدخل — قيد المراجعة", "التقرير الطبي — تم التحقق", "عرض سعر العلاج — عند الحاجة"].map((x, i) => <div className="flex items-center justify-between rounded-xl border p-3 text-sm" key={x}><span>{x}</span>{i === 1 ? <CircleAlert className="h-4 w-4 text-amber-500" /> : <CheckCircle2 className="h-4 w-4 text-[#32A88D]" />}</div>)}</div><div className="mt-6"><Button onClick={() => go("status")}>مراجعة وإرسال الطلب</Button></div></Panel>;
  return <div className="space-y-5"><Panel title={state === "approved" ? "تمت الموافقة على طلب التمويل" : "حالة طلب التمويل FIN-0001"} action={<StatusBadge state={state} />}>{state === "approved" && <div className="mb-5 rounded-xl bg-[#e6f6f2] p-4 text-sm text-[#1F6069]"><b>OMR 750</b> مبلغ معتمد بصورة توضيحية. بانتظار الاتفاق النهائي والتحقق من المزود.</div>}<Timeline state={state} /></Panel>{["disbursed", "treatment", "completed"].includes(state) && <Panel title="نظرة عامة على العلاج"><div className="grid gap-4 sm:grid-cols-3"><Info label="المزود" value="مركز النور للتأهيل" /><Info label="الخدمة" value="علاج طبيعي وتأهيلي" /><Info label="السداد" value="يديره البنك / هيكل التمويل" /></div></Panel>}</div>;
}
function StepProgress({ active }: { active: number }) { return <div className="flex items-center gap-1 overflow-x-auto">{["المعلومات", "الدخل", "الطلب", "المستندات", "المراجعة"].map((s, i) => <div key={s} className={`flex shrink-0 items-center gap-2 ${i + 1 <= active ? "text-[#1F6069]" : "text-gray-400"}`}><span className={`grid h-6 w-6 place-items-center rounded-full text-xs ${i + 1 <= active ? "bg-[#32A88D] text-white" : "bg-gray-100"}`}>{i + 1}</span><span className="text-xs font-bold">{s}</span>{i < 4 && <span className="mx-1 h-px w-5 bg-gray-200" />}</div>)}</div>; }
function Input({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <label className="block text-sm font-bold text-gray-700">{label}<input value={value} onChange={e => onChange(e.target.value)} inputMode="numeric" className="mt-2 w-full rounded-xl border border-gray-200 bg-white px-4 py-3 text-base outline-none focus:border-[#32A88D]" /></label>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-gray-50 p-4"><p className="text-xs text-gray-500">{label}</p><p className="mt-1 text-sm font-bold text-gray-800">{value}</p></div>; }
function Timeline({ state }: { state: DemoState }) { const current = state === "bankReview" || state === "moreInfo" ? 2 : state === "approved" ? 3 : state === "providerVerified" ? 4 : state === "disbursed" ? 5 : state === "treatment" ? 6 : state === "completed" ? 7 : 2; const items = ["التقييم الطبي", "الفحص المبدئي من MedNova", "مراجعة البنك", "التحقق من المزود", "الصرف", "العلاج", "الإكمال"]; return <div className="space-y-0">{items.map((item, i) => <div key={item} className="flex gap-4"><div className="flex flex-col items-center"><span className={`grid h-7 w-7 place-items-center rounded-full ${i < current ? "bg-[#32A88D] text-white" : i === current ? "bg-amber-400 text-white" : "bg-gray-100 text-gray-400"}`}>{i < current ? <Check className="h-4 w-4" /> : i + 1}</span>{i < items.length - 1 && <span className="h-7 w-px bg-gray-200" />}</div><div className="pt-1"><p className="text-sm font-bold">{item}</p><p className="text-xs text-gray-500">{i < current ? "مكتمل" : i === current ? statusMeta[state].label : "بانتظار القرار السابق"}</p></div></div>)}</div>; }

function Specialist({ state }: { state: DemoState }) { return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="استشارات معلقة" value="3" icon={Stethoscope} /><MetricCard label="تقارير لإكمالها" value="2" icon={FileText} /><MetricCard label="حالات معتمدة" value="4" icon={CheckCircle2} /><MetricCard label="علاجات جارية" value="6" icon={HeartPulse} /></div><Panel title="تقييم تمويل الرعاية الصحية — FIN-0001" action={<StatusBadge state={state} />}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Info label="المريض" value="أحمد الحارثي (بيانات تجريبية)" /><Info label="التشخيص / الحالة" value="إعادة تأهيل الركبة" /><Info label="الشدة" value="متوسطة" /><Info label="الضرورة الطبية" value="مثبتة في التقييم" /><Info label="التدخل الموصى به" value="علاج طبيعي وتأهيلي" /><Info label="الحاجة المالية التقديرية" value="OMR 750" /></div><div className="mt-5 rounded-xl border-r-4 border-[#32A88D] bg-[#f4fbf9] p-4 text-sm text-gray-700">التبرير السريري: يحتاج المريض تدخلاً تأهيلياً منظماً لاستعادة الحركة الوظيفية. التقرير يحدد الأهلية الطبية فقط، ولا يمثل قرار تمويل.</div><div className="mt-5"><Button>تم إرسال التقييم الطبي <Check className="h-4 w-4" /></Button></div></Panel></div>; }
function Admin({ state, go }: { state: DemoState; go: (p: Page) => void }) { return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="إجمالي الطلبات" value="28" icon={FileText} /><MetricCard label="مؤهل طبياً" value="15" icon={ShieldCheck} /><MetricCard label="مراجعة البنك" value={state === "bankReview" ? "4" : "3"} icon={Landmark} /><MetricCard label="معتمد" value={["approved","providerVerified","disbursed","treatment","completed"].includes(state) ? "8" : "7"} icon={CheckCircle2} /><MetricCard label="علاج نشط" value="6" icon={HeartPulse} /></div><Panel title="طلبات التمويل"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-right text-sm"><thead className="text-xs text-gray-500"><tr><th className="pb-3">المريض</th><th>الأهلية الطبية</th><th>المبلغ</th><th>حالة البنك</th><th>المزود</th><th>إجراء</th></tr></thead><tbody><tr className="border-t border-gray-100"><td className="py-4 font-bold">أحمد الحارثي<br /><span className="text-xs font-normal text-gray-500">FIN-0001</span></td><td><span className="text-[#1F6069]">مؤهل</span></td><td>OMR 750</td><td><StatusBadge state={state} /></td><td>مركز النور للتأهيل</td><td><button onClick={() => go("case")} className="font-bold text-[#32A88D]">فتح الحالة</button></td></tr></tbody></table></div></Panel>{pageCase(state)}</div>; }
function pageCase(state: DemoState) { return <Panel title="ملخص تشغيلي للحالة"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="المستندات" value="3 متحقق / 1 عند الحاجة" /><Info label="المزود" value={state === "providerVerified" ? "تم التحقق" : "بانتظار التحقق"} /><Info label="قرار البنك" value={state === "approved" ? "معتمد توضيحياً" : "قيد المراجعة"} /><Info label="سجل التدقيق" value="7 أحداث موثقة" /></div></Panel>; }
function Bank({ state, setState }: { state: DemoState; setState: (s: DemoState) => void }) { return <div className="space-y-5"><div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-900"><b>سير عمل توضيحي للشريك:</b> العملية البنكية النهائية تخضع للتكامل والاتفاق التعاقدي.</div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="طلبات جديدة" value="4" icon={FileText} /><MetricCard label="قيد المراجعة" value="7" icon={Landmark} /><MetricCard label="معلومات مطلوبة" value="2" icon={CircleAlert} /><MetricCard label="تمويل نشط" value="12" icon={Banknote} /></div><Panel title="طلب FIN-0001" action={<StatusBadge state={state} />}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Info label="المريض" value="أحمد الحارثي (بيانات تجريبية)" /><Info label="الأهلية الطبية" value="مؤهل — تقرير متاح" /><Info label="المبلغ المطلوب" value="OMR 750" /><Info label="المزود" value="مركز النور للتأهيل" /><Info label="مستندات الدعم" value="متاحة للمراجعة" /><Info label="المعلومات المالية" value="تطبق معايير البنك — للتأكيد" /></div><div className="mt-5 border-t pt-5"><p className="mb-3 font-bold">قرار التمويل</p><div className="flex flex-wrap gap-2"><Button secondary onClick={() => setState("moreInfo")}>طلب معلومات إضافية</Button><Button onClick={() => setState("approved")}>موافقة توضيحية <Check className="h-4 w-4" /></Button><button onClick={() => setState("rejected")} className="rounded-xl bg-rose-50 px-4 py-2.5 text-sm font-bold text-rose-700">رفض توضيحي</button></div></div></Panel></div>; }

function Investor({ state, go }: { state: DemoState; go: (p: Page) => void }) { return <div className="space-y-5"><div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-xs leading-5 text-blue-900">هيكل الاستثمار وإدارة الصندوق المعروض هنا <b>مفاهيمي</b> ويخضع للموافقات القانونية والتنظيمية والمصرفية.</div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="إجمالي رأس المال" value="OMR 120K" icon={WalletCards} /><MetricCard label="رأس المال المخصص" value="OMR 48K" icon={Banknote} /><MetricCard label="المتاح في المجمع" value="OMR 72K" icon={Activity} /><MetricCard label="تمويلات نشطة" value="18" icon={Users} /></div><Panel title="محفظة مفاهيمية"><div className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border p-4"><div className="flex justify-between"><b>FIN-0001</b><StatusBadge state={state} /></div><p className="mt-3 text-sm text-gray-600">تأهيل رعاية صحية · OMR 750 مخصص</p><p className="mt-3 text-xs text-gray-500">العائد والمدة يخضعان للهيكل المعتمد؛ ليسا عائداً مضموناً.</p></div><div className="rounded-xl border p-4"><div className="flex justify-between"><b>FIN-0002</b><span className="rounded-full bg-blue-50 px-3 py-1 text-xs text-blue-700">تقييم</span></div><p className="mt-3 text-sm text-gray-600">تدخل طبي · OMR 1,200 مقترح</p><p className="mt-3 text-xs text-gray-500">التعرض التمويلي يوضح كمفهوم عرض فقط.</p></div></div><div className="mt-5"><Button onClick={() => go("funding")}>عرض تدفق هيكل التمويل</Button></div></Panel></div>; }
function Funding({ state }: { state: DemoState }) { const items = ["مساهمات المستثمرين", "هيكل تمويل معتمد", "مجمع تمويل", "تمويل رعاية صحية معتمد", "المريض / المزود المتحقق", "السداد", "هيكل التمويل", "عائد المستثمر"]; return <Panel title="تسلسل هيكل التمويل المقترح"><p className="mb-6 text-sm text-gray-600">لا تدّعي هذه الشاشة أن MedNova تملك المجمع أو تتحكم في رأس المال.</p><div className="mx-auto max-w-md space-y-1">{items.map((item, i) => <div key={item} className="text-center"><div className={`rounded-xl p-4 text-sm font-bold ${i === 2 ? "bg-[#1F6069] text-white" : i === 3 ? "bg-[#e6f6f2] text-[#1F6069]" : "border bg-white"}`}>{item}{i === 3 && <span className="mr-2 text-xs font-normal">· {statusMeta[state].label}</span>}</div>{i < items.length - 1 && <ArrowDown className="mx-auto my-1 h-4 text-[#32A88D]" />}</div>)}</div></Panel>; }
function MoneyFlow({ flow, setFlow }: { flow: "patient" | "provider" | "controlled"; setFlow: (f: "patient" | "provider" | "controlled") => void }) { const labels = { patient: "البنك ← المريض ← المزود", provider: "البنك ← المزود المتحقق", controlled: "البنك ← حساب مصرح ومضبوط ← المزود" }; return <div className="space-y-5"><Panel title="تدفق الأموال المقترح"><div className="mb-5 flex flex-wrap gap-2">{(Object.keys(labels) as (keyof typeof labels)[]).map(key => <button onClick={() => setFlow(key)} className={`rounded-xl px-3 py-2 text-xs font-bold ${flow === key ? "bg-[#1F6069] text-white" : "bg-gray-100 text-gray-600"}`} key={key}>{labels[key]}</button>)}</div><p className="mb-5 text-sm text-gray-600">وجهة أموال التمويل <b>قرار مفتوح</b> للمصرف والجهات القانونية. النموذج المحدد أدناه هو تصور تفاعلي وليس هيكلاً نهائياً.</p><div className="grid items-center gap-3 md:grid-cols-5">{["المستثمر", "هيكل التمويل", "مجمع التمويل", "البنك", flow === "provider" ? "المزود المتحقق" : flow === "patient" ? "المريض ثم المزود" : "حساب مضبوط ثم المزود"].map((x, i) => <div className="flex items-center gap-2 md:block" key={x}><div className={`rounded-xl border p-4 text-center text-sm font-bold ${i === 2 ? "border-[#32A88D] bg-[#e6f6f2] text-[#1F6069]" : "bg-white"}`}>{x}</div>{i < 4 && <ArrowLeft className="h-4 shrink-0 text-[#32A88D] md:mx-auto md:my-2 md:rotate-180" />}</div>)}</div><div className="mt-6 grid gap-3 md:grid-cols-2"><div className="rounded-xl border-r-4 border-[#32A88D] bg-[#f4fbf9] p-4 text-sm"><b>تدفق التمويل:</b> رأس المال ← هيكل التمويل ← قرار التمويل المعتمد</div><div className="rounded-xl border-r-4 border-blue-400 bg-blue-50 p-4 text-sm"><b>السداد:</b> العميل ← البنك / هيكل التمويل ← العائد المحتمل للمستثمر</div></div><div className="mt-3 rounded-xl border-r-4 border-amber-400 bg-amber-50 p-4 text-sm"><b>إيراد MedNova التشغيلي:</b> يرتبط بموافقة التمويل فقط إذا تم الاتفاق عليه؛ الرسم والجهة الدافعة قيد التأكيد.</div></Panel><ResponsibilityMatrix /></div>; }
function ResponsibilityMatrix() { const rows = [["التقييم الطبي","✓","","✓",""],["الأهلية الطبية","✓","","✓",""],["التقييم الائتماني","","✓","",""],["قرار التمويل","","✓","",""],["التحقق من المزود","✓","","✓",""],["الصرف","","✓","",""],["العلاج","","","✓",""],["السداد","","✓","",""],["التمويل","","","","✓"],["عائد المستثمر","","البنك / الهيكل","","✓"]]; return <Panel title="مصفوفة المسؤوليات" action={<span className="text-xs text-amber-700">مقترح — يحتاج تحققاً</span>}><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-center text-sm"><thead><tr className="border-b text-gray-500"><th className="p-3 text-right">المسؤولية</th><th>MedNova</th><th>البنك</th><th>المزود</th><th>المستثمر</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-gray-50" key={row[0]}>{row.map((c, i) => <td className={`p-3 ${i === 0 ? "text-right font-bold" : c === "✓" ? "font-bold text-[#32A88D]" : "text-xs text-gray-500"}`} key={`${row[0]}${i}`}>{c}</td>)}</tr>)}</tbody></table></div></Panel>; }

function Criteria() { const sections = [{ title: "المعايير الطبية", values: ["حاجة طبية متحققة", "استشارة تشخيصية مكتملة", "أخصائي مرخص / معتمد", "تقرير طبي متاح", "الحالة ضمن نطاق الرعاية المدعوم", "حاجة قابلة للتحقق سريرياً"] }, { title: "معايير المريض", values: ["العمر: قيد التأكيد", "الإقامة: قيد التأكيد", "الدخل: معايير البنك", "العمل: معايير البنك", "التاريخ الائتماني: معايير البنك"] }, { title: "معايير التمويل", values: ["الحد الأعلى: قيد التأكيد", "الحد الأدنى: قيد التأكيد", "المدة: قرار البنك", "الرسوم: قيد التأكيد"] }, { title: "معايير المزود", values: ["مزود مرخص / معتمد", "خدمة صالحة", "هوية متحققة", "بيانات دفع متحققة", "عرض سعر / مستندات مطلوبة"] }]; return <div className="grid gap-5 md:grid-cols-2">{sections.map(s => <Panel title={s.title} key={s.title} action={<span className="text-xs text-amber-700">مقترح</span>}><ul className="space-y-3">{s.values.map(v => <li className="flex gap-2 text-sm text-gray-700" key={v}><CheckCircle2 className="h-4 w-4 shrink-0 text-[#32A88D]" />{v}</li>)}</ul><p className="mt-5 text-xs text-gray-500">خاضع للتحقق مع البنك والجهات القانونية.</p></Panel>)}</div>; }
function OpenDecisions() { const questions = ["ما الدور الدقيق الذي ينبغي أن يؤديه البنك في النموذج؟", "من يملك قرار التمويل؟", "هل على MedNova الفحص المبدئي قبل مراجعة البنك؟", "ما معايير الأهلية المالية التي يوفرها البنك؟", "أين تصرف أموال التمويل المعتمدة؟", "هل يمكن الدفع مباشرة لمزودي الرعاية المتحققين؟", "هل يمكن أن تعمل MedNova كوسيط أو وكيل مصرح؟", "أين يجب أن يقيم رأس مال المستثمرين قانونياً؟", "من يملك حفظ وسيطرة مجمع التمويل؟", "كيف يتم تحصيل السداد؟", "كيف يحسب ويوزع عائد المستثمر؟", "ما نقاط API والتكامل التي يدعمها البنك؟", "ما بيانات العميل التي يمكن إرسالها للبنك؟", "ما المستندات المطلوبة؟", "ما متطلبات الامتثال وKYC وAML؟"]; return <div className="space-y-5"><Panel><div className="max-w-3xl"><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">أجندة قرار الشراكة</span><h2 className="mt-4 text-2xl font-bold">ما الذي نحتاج لتأكيده مع البنك؟</h2><p className="mt-2 text-sm leading-6 text-gray-600">هذه ليست شروطاً مقررة. إنها نقاط قرار مصممة لتوجيه النقاش التجاري والقانوني والتنظيمي في الاجتماع.</p></div></Panel><div className="grid gap-3 md:grid-cols-2">{questions.map((q, i) => <div key={q} className="flex gap-4 rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[#e6f6f2] text-xs font-bold text-[#1F6069]">{i + 1}</span><p className="text-sm font-bold leading-6">{q}</p></div>)}</div></div>; }
function DemoControls({ state, setState, reset }: { state: DemoState; setState: (s: DemoState) => void; reset: () => void }) { return <div className="fixed bottom-3 left-3 z-40 max-w-[calc(100vw-24px)] rounded-2xl border border-gray-200 bg-white/95 p-2 shadow-xl backdrop-blur"><div className="flex max-w-[760px] flex-wrap items-center gap-1.5"><span className="px-2 text-xs font-bold text-[#1F6069]">عناصر العرض</span><button onClick={reset} className="rounded-lg px-2 py-1.5 text-xs font-bold text-gray-600 hover:bg-gray-100"><RefreshCw className="ml-1 inline h-3 w-3" />إعادة</button>{([ ["موافقة", "approved"], ["تحقق المزود", "providerVerified"], ["صرف", "disbursed"], ["بدء العلاج", "treatment"], ["إكمال", "completed"], ["معلومات", "moreInfo"] ] as [string, DemoState][]).map(([label, next]) => <button key={next} onClick={() => setState(next)} disabled={state === next} className="rounded-lg bg-[#f1faf7] px-2 py-1.5 text-xs font-bold text-[#1F6069] hover:bg-[#e0f3ed] disabled:opacity-50">{label}</button>)}</div></div>; }
